/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tccc.view.Paineis;

import com.lowagie.text.BadElementException;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.decorator.ColorHighlighter;
import org.jdesktop.swingx.decorator.HighlightPredicate;
import org.jdesktop.swingx.decorator.PatternPredicate;
import tccc.ControleDeColuna;
import tccc.DAO.PesquisarProdutosEstoqueDAO;
import tccc.GerarPDF;

/**
 *
 * @author Efraim
 */
public class Painel_TelaEstoque extends javax.swing.JPanel {

    PesquisarProdutosEstoqueDAO dao = new PesquisarProdutosEstoqueDAO();

    public Painel_TelaEstoque() {
        initComponents();
        ListarTabela();
    }

    public void ListarTabela() {
        PesquisarProdutosEstoqueDAO dao = new PesquisarProdutosEstoqueDAO();
        dao.ListarTabela(TblEstoque);
        ControleDeColuna c = new ControleDeColuna(TblEstoque, true);

        HighlightPredicate predicate = new PatternPredicate("! ", 1);
        ColorHighlighter highlighter = new ColorHighlighter(predicate, Color.red, null, null, null);
        TblEstoque.setHighlighters(highlighter);

//        String tt;
//        for (int i = 0; i <= TblEstoque.getRowCount() - 1; i++) {
//            tt = String.valueOf(TblEstoque.getValueAt(i, 1));
//            tt = tt.replace("! ", "");
//            System.out.println(tt);
//            TblEstoque.getModel().setValueAt(tt, i, 1);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        BotaoImprimir = new javax.swing.JLabel();
        LblImprimir = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        CbCampo = new javax.swing.JComboBox<>();
        TxtPesquisa = new javax.swing.JFormattedTextField();
        BotaoPesquisar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblEstoque = new org.jdesktop.swingx.JXTable();

        setPreferredSize(new java.awt.Dimension(870, 410));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(870, 410));

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        BotaoImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tccc/Imagens/icons8_Print_65px.png"))); // NOI18N
        BotaoImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoImprimirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoImprimirMouseEntered(evt);
            }
        });

        LblImprimir.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        LblImprimir.setForeground(new java.awt.Color(255, 255, 255));
        LblImprimir.setText("Relátorio");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(LblImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotaoImprimir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblImprimir))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CbCampo.setForeground(new java.awt.Color(255, 255, 255));
        CbCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "ID", "Descrição", "Marca" }));
        CbCampo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbCampoItemStateChanged(evt);
            }
        });
        CbCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbCampoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CbCampoMousePressed(evt);
            }
        });
        jPanel6.add(CbCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 40, 90, -1));

        TxtPesquisa.setBorder(null);
        TxtPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        TxtPesquisa.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        TxtPesquisa.setPreferredSize(new java.awt.Dimension(4, 24));
        jPanel6.add(TxtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 44, 140, 20));

        BotaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tccc/Imagens/icons8_Search_26px_1.png"))); // NOI18N
        BotaoPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoPesquisarMouseExited(evt);
            }
        });
        jPanel6.add(BotaoPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 30, 50));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Pesquisar");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 290, -1));

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        TblEstoque.setForeground(new java.awt.Color(255, 255, 255));
        TblEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Produto", "Produto", "Marca", "Quantidade Atual", "Estoque Mínimo"
            }
        ));
        TblEstoque.setToolTipText("");
        TblEstoque.setEditable(false);
        TblEstoque.setFillsViewportHeight(false);
        TblEstoque.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TblEstoque.setGridColor(new java.awt.Color(0, 0, 0));
        TblEstoque.setHorizontalScrollEnabled(true);
        TblEstoque.setSearchable(null);
        TblEstoque.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(TblEstoque);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoImprimirMouseClicked
        try {
            GerarPDF pdf = new GerarPDF();
            pdf.criarPDF(TblEstoque, "RelatorioEstoque");
            pdf.abrirPDF("RelatorioEstoque");
        } catch (BadElementException ex) {
             JOptionPane.showMessageDialog(null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_BotaoImprimirMouseClicked

    private void BotaoImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoImprimirMouseEntered
        BotaoImprimir.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotaoImprimirMouseEntered

    private void CbCampoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbCampoItemStateChanged
        TxtPesquisa.setText("");
        try {
            if (CbCampo.getSelectedIndex() == 0) {
                dao.Pesquisar1("IdTB_Produto", "", TblEstoque);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_CbCampoItemStateChanged

    private void CbCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbCampoMouseClicked

    }//GEN-LAST:event_CbCampoMouseClicked

    private void CbCampoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbCampoMousePressed

    }//GEN-LAST:event_CbCampoMousePressed

    private void BotaoPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoPesquisarMouseClicked
        String campo = null;

        switch (CbCampo.getSelectedIndex()) {
            case 1:
                campo = "IdTB_Produto";
                dao.Pesquisar1(campo, TxtPesquisa.getText(), TblEstoque);
                break;
            case 2:
                campo = "Produto_Descricao";
                dao.Pesquisar1(campo, TxtPesquisa.getText(), TblEstoque);
                break;
            case 3:
                campo = "Marca_Descricao";
                dao.Pesquisar1(campo, TxtPesquisa.getText(), TblEstoque);
                break;
            default:
                campo = "IdTB_Produto";
                dao.Pesquisar1(campo, TxtPesquisa.getText(), TblEstoque);
                break;
        }
    }//GEN-LAST:event_BotaoPesquisarMouseClicked

    private void BotaoPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoPesquisarMouseEntered
        BotaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tccc/Imagens/icons8_Search_26px_3.png")));
        BotaoPesquisar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BotaoPesquisarMouseEntered

    private void BotaoPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoPesquisarMouseExited
        BotaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tccc/Imagens/icons8_Search_26px_1.png")));
    }//GEN-LAST:event_BotaoPesquisarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotaoImprimir;
    private javax.swing.JLabel BotaoPesquisar;
    private javax.swing.JComboBox<String> CbCampo;
    private javax.swing.JLabel LblImprimir;
    private org.jdesktop.swingx.JXTable TblEstoque;
    private javax.swing.JFormattedTextField TxtPesquisa;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
